#!/bin/bash                                                                                                                                                                   
#PBS -N incompress                                                                                                                        
#PBS -A ufq-485-ac                                                                                                                         
#PBS -l walltime=10000                                                                                                                   
#PBS -l nodes=4:ppn=8                                                                                                                           
#PBS -e $HOME/job.err                                                                                                                            
#PBS -o $HOME/job.out                                                                                                                                

module load compilers/intel/14.0
module load mpi/openmpi/1.6.5
module load libs/fftw/3.3.3
module load libs/mkl/11.1


#Execute (I move stuff so everything appears in the wanted directory, not sure it's optimal #                                                            
mv $HOME/solver_2.0/exec_qg $HOME/output
cd $HOME/output

mpirun -np 32 ./exec_qg

mv $HOME/output/exec_qg $HOME/solver_2.0/exec_qg
#cd $HOME                                                                                                                                            
#rm *.mod  